Fix train from file
Unbabel/OpenKiwi pull request #76
Opened 2020-10-21 13:40 UTC by captainvera

The function kiwi.lib.train.train_from_file was not working as expected for two different reasons:

1. It expected a Path object, so calling it as:
```
from kiwi.lib.train import train_from_file
run_info = train_from_file('config/bert.yaml')
```
Did not work.

2. We were loading the config file directly and not passing it through hydra, this made it so that `defaults` weren't being processed. 

This PR fixes both issues.

2020-10-22 02:33 UTC, Shannen3206 commented
The problem has been solved, thank you very much for your help, your rigorous academic attitude is worth learning.

2020-10-22 12:27 UTC, kepler requested changes
Missing a test. :)

What if `file_to_configuration` is called twice? There were some problems with Hydra when doing that in the `search` pipeline.

2020-10-23 12:35 UTC, captainvera commented
@kepler this has been reviewed. Tests and Docstrings added.

2020-10-23 13:11 UTC, kepler approved these changes

2020-10-23 14:19 UTC, merged